### ISSUE TITLE
Loading unnecessary dependencies

### ISSUE THREAD

**Issue by iksose** [swimlane-contrib/systemjs-route-bundler#25]
https://github.com/iksose/systemjs-seed

in my `app/subroute` I declare a moment.js dependency, and if I navigate to the home state first it only loads that slug when I request that state. However, if I load `subroute` first it also loads the main "slug". 

Am I declaring my modules wrong?

**Comment by marjan-georgiev** [comment]
Can you elaborate please?

**Comment by iksose** [comment]
I think it may be an issue with how https://github.com/lookfirst/systemjs-seed is doing it, which is what I forked so it may be more appropriate for me to open the issue there. But essentially if I go to `/` , it'll load the next states deps only when requested (intended behavior) but if I start my app by first going to `/foo` it'll bring in everything. I'm sure I'm missing something.

**Comment by lookfirst** [comment]
Watching too... this could be something I've messed up I'm sure. =) Are you running it in `SITUATION=production`?

**Comment by marjan-georgiev** [comment]
Your root module (app.js) is always going to be loaded, no matter which route you land to.

It's the entry point of the app and imported by your index file: 
https://github.com/iksose/systemjs-seed/blob/master/src/index.tpl.html#L46

**Comment by iksose** [comment]
ex: `http://localhost:9000/#/subroute2`

![screen shot 2015-04-22 at 2 00 58 pm](https://cloud.githubusercontent.com/assets/3856245/7282798/09818b7c-e8f8-11e4-9cdd-47c424930e86.png)

Specifically loading `http://localhost:9000/app/subroute/subroute.js?bust=1429729189"` and `/app/subroute2/subroute.js` when afaik there's no dependencies between the two?

@lookfirst Yeah I've tried both env variables.

So given three routes: `home`, `foo`, `bar`

Entry `home` => click route `foo`, loads `foo` => click `bar`, loads `bar`. Perfect.
If the entry point is `foo`, it loads `home` && `foo`. Unintended?
And now if entry point is `bar`, it loads everything -- `bar`, `foo`, and `home`. Also Unintended?

**Comment by lookfirst** [comment]
The bundling only happens in production mode, so you absolutely need to be using that in order to file bugs here. :smile:

I'm confused though, browserSync shouldn't be enabled when you are in production mode and I'm seeing stuff in your console.log(). What's confusing is that I'm also seeing the `bust=` parameter too. Did you change something in the gulpfile that would break this?

**Comment by lookfirst** [comment]
The way I have things in my project, if you load foo (todo), it will load home (app).

**Comment by iksose** [comment]
Yeah its production mode, its almost all standard except for the things you pointed out which shouldn't cause `/foo2` to load `/foo`

I'm just using browsersync to serve the compiled/bundled app

**Comment by lookfirst** [comment]
gulp-helpers has bs built in. I don't understand why you added a separate task for it. 

What you've done is [removed a bit of configuration that is crucial](https://github.com/iksose/systemjs-seed/blob/51ea3365edabd38d42314035f419281c6225cbfb/gulpfile.js#L81)... you don't want BS to be doing its thing in production.

**Comment by iksose** [comment]
idk, but it's fixed now! ...and I have no idea what changed. Could have been my modifications to BS that you mentioned.

So yeah now I can navigate to `foo` and it won't load `home` (in addition to `app.js` which is obviously core)
