### ISSUE TITLE
Process Hangs on Windows Machines.

### ISSUE THREAD

**Issue by cliechty** [swimlane-contrib/systemjs-route-bundler#26]
When I try to bundle routes (testing with systemjs-seed project) the bundler hangs and the node process is pegging the CPU. On my mac the bundler processes fine and fairly quickly. 

The output I get on a windows machine when it hangs is:

```
[13:54:51] Running as: development
[13:54:57] Using gulpfile C:\code\js\systemjs-seed\gulpfile.js
[13:54:57] Starting 'routeBundler'...
tracing source files...
generating bundles...
building...
building bundles...
building routes...
building app...
```
##### To replicate:
1. clone project: https://github.com/lookfirst/systemjs-seed 
2. run `npm install`
3. run `jspm install`
4. run `gulp recompile`
5. run `gulp routerBundler`

I have verified that the issue exists with node 0.10.x and 0.12.x. It looks almost like the process is getting stuck in an infinite loop on windows machines.

My Windows config is:
- Windows 7 pro 64bit
- Intel Core i5-2320 @ 3.00Ghz

**Comment by lookfirst** [comment]
JavaScript... Write once, run _almost_ anywhere! :wink:

**Comment by lookfirst** [comment]
I'm working today on upgrading to latest of this project...

**Comment by cliechty** [comment]
I found out what is causing the issue on windows. Turns out that builder is writing the files from npm, github, etc into the **'dest'** folder, prefixing them with the repo:packagename ex: `npm:react@0.13.1.js`. In windows **':'** is not a valid character in a file or directory name.

As a side note; shouldn't all of the referenced files be bundled?

**Comment by marjan-georgiev** [comment]
@cliechty thank you for catching that!

Those files are currently bundled, but also built separately (which is unnecessary). I'll push a fix for this today.

**Comment by amcdnl** [comment]
@cliechty don't use windows ;)

**Comment by lookfirst** [comment]
Oh yea, I noticed all those folders getting created in my dest folder. Would be nice to not have those. =)

:+1: on not using windows!

**Comment by cliechty** [comment]
Unfortunately those who pay my salary force me to use windows. :frowning:

**Comment by lookfirst** [comment]
I think I'd bring my own computer to work then. ;-)

**Comment by marjan-georgiev** [comment]
I pushed a fix. Please upgrade your project to use 1.1.1

**Comment by cliechty** [comment]
I have confirmed the issue is fixed. Thanks for the quick turnaround. This project looks like it will really help my teams project in the near future.
