### ISSUE TITLE
Any plan to update for SystemJS 0.17 & 0.18?

### ISSUE THREAD

**Issue by wmulligan** [swimlane-contrib/systemjs-route-bundler#29]
SystemJS 0.17 has major changes, any plan to update this library?

**Comment by amcdnl** [comment]
SystemJS moves so fast!  We are planning to in the next couple of weeks but if you wanted to do a PR in the meantime, more than welcome!

**Comment by marjan-georgiev** [comment]
We're up to date with systemjs 0.18.4 and jspm 0.16 beta now
