### ISSUE TITLE
node-v8-clone doesn't work with iojs

### ISSUE THREAD

**Issue by pauleveritt** [swimlane-contrib/systemjs-route-bundler#30]
Per AlexeyKupershtokh/node-v8-clone#8 and it's likely something that affects more recent NodeJS releases.

**Comment by marjan-georgiev** [comment]
@pauleveritt thanks for the heads up! I'll look for replacement if it doesn't get fixed soon.

**Comment by brettstack** [comment]
Still an issue with latest NodeJS. Confirmed working with node 0.10.40

**Comment by brettstack** [comment]
Any chance we can get an alternative to node-v8-clone? Maybe https://www.npmjs.com/package/clone. this is a blocker for those who need more recent versions of node (myself included)

**Comment by marjan-georgiev** [comment]
#33 should have fixed this. Please reopen if you still see the problem.
