### ISSUE TITLE
Issues when main file is in a different directory

### ISSUE THREAD

**Issue by brettstack** [swimlane-contrib/systemjs-route-bundler#32]
Since this was made to work with the angular-systemjs-seed repo, it assumes a certain directory structure. However, it would be useful if it could be used with other directory structures also. My directory structure differs in that instead of having a single `dist` folder I have `builds/debug` and `builds/release`.

Currently, my main file which exists at `builds/debug/app/app.js` gets skipped due to this line https://github.com/Swimlane/systemjs-route-bundler/blob/3e06f73f8fad28317c8ca605d1fc2a9dfde4e068/lib/builder.js#L208. I can get it building by adding `if (destination !== config.main && ...){`, however then the problem becomes that it is being built to the root directory of my project instead of `builds/release/app/app.js`. This is because the moduleName/destination is 'app/app'. I can solve this by changing https://github.com/Swimlane/systemjs-route-bundler/blob/3e06f73f8fad28317c8ca605d1fc2a9dfde4e068/lib/builder.js#L182 to:

```
var destination = isMainModule ? config.destJs : moduleName;
buildTree(appTree[moduleName], destination, config).then(function () {
```

I've just created a PR at #31 which also fixes output directories (appapp and appbundles)

**Comment by marjan-georgiev** [comment]
@breandr - Could you create an example repo with your configuration, please? Your pull request didn't work for our use case. I've released a new version (1.3.0) with more configuration options, and I want to make sure I cover your use case.

I updated the angular-systemjs-seed repo to work with the latest version of the bundler.

Thanks!

**Comment by brettstack** [comment]
Unfortunately I can't post anything as it's a private project, but I have upgraded to the latest and it now outputs the app.js, however it did introduce other issues.

I see that you have changed your paths in system.config so that they no longer map to a .js extension. I am unable to get this to work as it means all System.import calls will no longer include the .js extension automatically. If I add the .js extensions back into the path mappings and in my bundler config I set main to 'app/app' (instead of 'app/app.js'  as in the seed project), it successfully bundles and outputs to my release directory. However, the files do not include the ".js" extension. So for example my 'app.js' file (and all other files) comes out as 'builds/release/app' with no extension.

**Comment by marjan-georgiev** [comment]
Do you have this line in your systemjs config file?

https://github.com/Swimlane/angular-systemjs-seed/blob/master/system.config.js#L3

**Comment by brettstack** [comment]
Yes, I tried that previously which presents new problems. In my index.html I call `System.import('app/app')` which gives 404 because it is looking for a file called 'app/app', but the file exists on disk as 'app/app.js'

**Comment by marjan-georgiev** [comment]
What versions of jspm and systemjs are you using?

**Comment by brettstack** [comment]
Ahh. I missed that you upgraded to the latest jspm beta. I updated and it works! This is brilliant! Thank you so much.

**Comment by marjan-georgiev** [comment]
You're welcome. Glad it works!

**Comment by amcdnl** [comment]
@breandr are you using it @ Amazon?

**Comment by brettstack** [comment]
Yes. Experimental.

**Comment by amcdnl** [comment]
Very cool.  Look forward to hearing more feedback from ya!
