### ISSUE TITLE
Move node-v8-clone to optional dependencies

### ISSUE THREAD

**Issue by maxlk** [swimlane-contrib/systemjs-route-bundler#33]
I suggest to move node-v8-clone to optional dependencies since it is not functional but performance requirement, and it introduces many compatibility issues to this project and dependants of this project ([lookfirst/gulp-helpers](https://github.com/lookfirst/gulp-helpers), [lookfirst/systemjs-seed](https://github.com/lookfirst/systemjs-seed), etc.).
Compatibility issues to mention:
- Hard dependency on Microsoft Visual Studio C++ 2013 and Python on Windows AlexeyKupershtokh/node-v8-clone#12
- io.js incompatibility Swimlane/systemjs-route-bundler#30

**Comment by marjan-georgiev** [comment]
Thanks! Is it possible to completely remove node-v8-clone though? @breandr suggested https://www.npmjs.com/package/clone as an alternative. 

If we can get rid of node-v8-clone completely, I'm all for it.

**Comment by maxlk** [comment]
You don't really need https://www.npmjs.com/package/clone, since it is intended for deep-copying of complex objects. What you need is a simple shallow-copying of objects, so `for(in)` do the job.

Pull request #34 contains logic which uses _node-v8-clone_ when it is available and fallbacks to `for(in)` when it's not. The only reason to use _node-v8-clone_ is a performance gain that it provides in case of heavy object cloning. I don't know how much is it for _systemjs-route-bundler_, I didn't find any performance tests here and my project is too small to load it.

If you need a performance, accept the pull request as is. If you don't need it, just confirm and I will remove it completely.

**Comment by brettstack** [comment]
Any chance of getting this merged? Thanks.

**Comment by marjan-georgiev** [comment]
Merged. It's in 1.3.4

Thanks!
