### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by lookfirst** [swimlane-contrib/systemjs-route-bundler#4]
1. update version to 1.0.2
2. npm publish

the reason is the readme file is old.

**Comment by lookfirst** [comment]
not really a bug. i've updated the version and now that you've merged. i'll do the push.

**Comment by lookfirst** [comment]
pushed

**Comment by amcdnl** [comment]
thanks!  been a hectic week.

**Comment by lookfirst** [comment]
sorry to add to your load... just trying to get all this working... =)

**Comment by amcdnl** [comment]
not a problem :)

**Comment by amcdnl** [comment]
@lookfirst can you add @marjan-georgiev as a contrib?

**Comment by lookfirst** [comment]
@amcdnl done, but for future reference, you should have had access to do it too. `npm owner add marjan-georgiev`

**Comment by amcdnl** [comment]
Thnx
