### ISSUE TITLE
Cannot read property 'tree' of undefined

### ISSUE THREAD

**Issue by zeeshanjan82** [swimlane-contrib/systemjs-route-bundler#40]
After I have integrated the systemjs-route-bundler in my gulp and when I issue the command 'gulp bundle' everything works fine except at the end I get the error

``` js
TypeError:Cannot read property 'tree' of undefined
```

This error does come in the lib/builder.js file
I am using Node v4.1.1

**Comment by zeeshanjan82** [comment]
More digging shows that the issue comes when I have more that 1 state in routes.json file. If I have only one state or route then the gulp build release command works fine. The error comes in the method: generateBundles

**Comment by marjan-georgiev** [comment]
Could you create a github repo where this is replicated please? You can fork the seed project and do the changes you did to get this.

**Comment by zeeshanjan82** [comment]
I have managed to find the cause of this issue, I had some js files which had names like app.js , socket.js in my project and when I renamed them to application.js , sockets.js then the gulp bundle command worked fine. I am sure it is because of the names collision.

**Comment by marjan-georgiev** [comment]
Great! I'll close this issue then.

**Comment by zeeshanjan82** [comment]
Thanks @marjan-georgiev

**Comment by zeeshanjan82** [comment]
I would like to reopen this issue as its not related to file names, something is wrong with systemjs-route-bundler or I am not able to understand it well. Here is the scenario:
I have an angular service which I have imported in my login screen and from my login screen I navigate to registration screen. Both Login and Registration are 2 different routes defined in the routes.json file.
This perticular service is already referenced in Login module and when I reference it again in registration module I get the error 'Cannot read property 'tree' of undefined' in the builder.js line 100
I get undefined when I try to use 

``` js
console.log(appTree[mainName]);
```

![image](https://cloud.githubusercontent.com/assets/8342604/10562644/4f316e6c-7584-11e5-9142-dac3c2039f67.png)

**Comment by zeeshanjan82** [comment]
OK I have found the reason (I think) Its a bug in the library. I have my main module name as app.js and the service name is appManager.js. Its because of the 'app' which is common between the both.

**Comment by zeeshanjan82** [comment]
Today I again faced the issue with the same file I had renamed the file yesterday from appManager to Manager but today even its not accepting Manager as filename. I am not sure why did it work yesterday. I am so frustrated with this issue that I am on the edge of just quitting with this seed project and using systemjs-route-bundler. It has become more buggy.

**Comment by zeeshanjan82** [comment]
Any update on this?

**Comment by amcdnl** [comment]
This seems application specific, i will need a exact demo to reproduce.

**Comment by MilaDevSt** [comment]
We had the same problem.We resolved it by removing bundleThreshold parameter in systemjs-bundler configuration in our gulp task.
