### ISSUE TITLE
Is this project updated/maintained?

### ISSUE THREAD

**Issue by benjamingr** [swimlane-contrib/systemjs-route-bundler#41]

**Comment by marjan-georgiev** [comment]
Yes, it's used in https://github.com/Swimlane/angular-systemjs-seed.

**Comment by benjamingr** [comment]
Thanks. Didn't see any commits in 3 months.

**Comment by amcdnl** [comment]
We use it EVERYDAY in our production app, as we find issues we are always fixing/etc.
